INSERT INTO "Product" (
  "id",
  "sku",
  "slug",
  "name",
  "subtitle",
  "price",
  "collection",
  "category",
  "fit",
  "badge",
  "description",
  "story",
  "vibe",
  "materials",
  "leadTime",
  "sizes",
  "highlights",
  "paletteBase",
  "paletteShell",
  "paletteAccent",
  "paletteGlow",
  "paletteText",
  "storefrontImage",
  "catalogImages",
  "inventory",
  "active",
  "featured",
  "createdAt",
  "updatedAt"
)
VALUES
(
  'product_opposite_day_uniform',
  'OD',
  'opposite-day-uniform',
  'Opposite Day Uniform',
  'Contrasting tee for mixed signals',
  1099,
  'Contrasting T-Shirt Designs',
  'Graphic Tee',
  'Oversized',
  'Two moods',
  'A split-personality tee for people who can disagree with themselves and still make it look intentional.',
  'Built around clashing panels, opposite moods, and a graphic layout that turns indecision into the entire point.',
  'Clean from far away, questionable up close, exactly on brand.',
  '230 GSM soft cotton',
  'Dispatches in 72 hours',
  ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Split-front graphic', 'Oversized contrast fit', 'Soft ribbed collar']::TEXT[],
  '#ffffff',
  '#111111',
  '#ffd93d',
  '#ff5f7a',
  '#17120a',
  NULL,
  ARRAY[]::TEXT[],
  24,
  true,
  false,
  NOW(),
  NOW()
),
(
  'product_double_take_department',
  'DT',
  'double-take-department',
  'Double Take Department',
  'Contrasting tee for impossible choices',
  1199,
  'Contrasting T-Shirt Designs',
  'Statement Tee',
  'Boxy',
  'Visual argument',
  'Looks calm until the design starts arguing with itself. Useful for people with two tabs open in their personality.',
  'A sharper contrast drop with loud type, clean blocking, and just enough visual conflict to make strangers look twice.',
  'Graphic, split, and built for main-character confusion.',
  '240 GSM combed cotton',
  'Made to order in 4 days',
  ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Boxy crop', 'High-contrast print', 'Front and back graphic']::TEXT[],
  '#17120a',
  '#ffffff',
  '#ffcf24',
  '#2563eb',
  '#ffffff',
  NULL,
  ARRAY[]::TEXT[],
  24,
  true,
  false,
  NOW(),
  NOW()
)
ON CONFLICT ("slug") DO UPDATE
SET "sku" = EXCLUDED."sku",
    "name" = EXCLUDED."name",
    "subtitle" = EXCLUDED."subtitle",
    "price" = EXCLUDED."price",
    "collection" = EXCLUDED."collection",
    "category" = EXCLUDED."category",
    "fit" = EXCLUDED."fit",
    "badge" = EXCLUDED."badge",
    "description" = EXCLUDED."description",
    "story" = EXCLUDED."story",
    "vibe" = EXCLUDED."vibe",
    "materials" = EXCLUDED."materials",
    "leadTime" = EXCLUDED."leadTime",
    "sizes" = EXCLUDED."sizes",
    "highlights" = EXCLUDED."highlights",
    "paletteBase" = EXCLUDED."paletteBase",
    "paletteShell" = EXCLUDED."paletteShell",
    "paletteAccent" = EXCLUDED."paletteAccent",
    "paletteGlow" = EXCLUDED."paletteGlow",
    "paletteText" = EXCLUDED."paletteText",
    "active" = EXCLUDED."active",
    "updatedAt" = NOW();
