INSERT INTO "Product" (
  "id", "sku", "slug", "name", "subtitle", "price", "collection", "category",
  "fit", "badge", "description", "story", "vibe", "materials", "leadTime",
  "sizes", "highlights", "paletteBase", "paletteShell", "paletteAccent",
  "paletteGlow", "paletteText", "storefrontImage", "catalogImages",
  "inventory", "active", "featured", "createdAt", "updatedAt"
)
VALUES
(
  'product_consider_your_pants_peed', 'CP', 'consider-your-pants-peed',
  'Consider Your Pants Peed', 'Brainrot tee for cursed warnings', 999,
  'Brainrot', 'Meme Tee', 'Oversized', 'Threat level wet',
  'A black tee for people who prefer their threats delivered by a deeply unserious cat.',
  'The print has old-internet energy, suspicious blue lightning, and exactly the kind of message nobody asked to receive.',
  'Chaotic, loud, and impossible to explain politely.', '230 GSM combed cotton',
  'Dispatches in 72 hours', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Oversized black tee', 'Large front meme print', 'Soft ribbed collar']::TEXT[],
  '#101010', '#ffffff', '#7dd3fc', '#ffcf24', '#ffffff',
  '/images/products/consider-your-pants-peed-shirt.png',
  ARRAY['/images/products/consider-your-pants-peed-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_cahfih', 'CF', 'cahfih', 'Cahfih',
  'Brainrot tee for animal typos', 999, 'Brainrot', 'Meme Tee', 'Relaxed',
  'Specimen detected',
  'A clean white tee featuring a catfish that took the assignment too literally.',
  'Part cat, part fish, fully a spelling problem. This is the kind of shirt that rewards people for staring one second longer.',
  'Dry, stupid, and unexpectedly calm.', '220 GSM soft cotton',
  'Dispatches in 48 hours', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['White tee base', 'Catfish front graphic', 'Relaxed daily fit']::TEXT[],
  '#f8f3df', '#ffffff', '#111111', '#ffcf24', '#17120a',
  '/images/products/cahfih-shirt.png',
  ARRAY['/images/products/cahfih-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_laughed_it_off', 'LO', 'laughed-it-off', 'Laughed It Off',
  'Dark humor tee for coping badly', 1099, 'Brainrot', 'Dark Humor Tee',
  'Oversized', 'Coping mechanism',
  'A minimal white tee for anyone whose emotional strategy is making the joke first.',
  'Thin-line art, quiet delivery, and a punchline that sits somewhere between therapy and group chat damage.',
  'Deadpan, uncomfortable, and clean enough to pass as normal.', '230 GSM soft cotton',
  'Dispatches in 72 hours', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Minimal black print', 'Oversized white tee', 'Soft everyday cotton']::TEXT[],
  '#f8f6ee', '#ffffff', '#111111', '#ff5f7a', '#17120a',
  '/images/products/laughed-it-off-shirt.png',
  ARRAY['/images/products/laughed-it-off-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_very_old_picture_of_me', 'VOP', 'very-old-picture-of-me',
  'Very Old Picture Of Me', 'Brainrot tee for ancient lore', 999,
  'Brainrot', 'Meme Tee', 'Oversized', 'Origin story',
  'A white tee with the most technically correct baby picture possible.',
  'The design is simple, stupid, and biologically committed to the bit. Great for people with too much lore.',
  'Low-effort genius with science-class trauma.', '220 GSM soft cotton',
  'Dispatches in 48 hours', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Square front print', 'White tee base', 'Soft ribbed collar']::TEXT[],
  '#f8f6ee', '#ffffff', '#111111', '#ffcf24', '#17120a',
  '/images/products/very-old-picture-shirt.png',
  ARRAY['/images/products/very-old-picture-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_hoxeless', 'HX', 'hoxeless', 'Hoxeless',
  'Black tee for typo pessimists', 1099, 'Brainrot', 'Statement Tee',
  'Boxy', 'Hope typo',
  'A black tee for when optimism gets crossed out before it even finishes loading.',
  'Bold type, one red strike, and the exact amount of negativity required for a Monday morning.',
  'Sharp, blunt, and intentionally incorrect.', '240 GSM combed cotton',
  'Made to order in 4 days', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Black boxy tee', 'Bold chest text', 'Red strike detail']::TEXT[],
  '#101010', '#ffffff', '#ef4444', '#ffcf24', '#ffffff',
  '/images/products/hoxeless-shirt.png',
  ARRAY['/images/products/hoxeless-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_one_piece_of_shirt', 'OPS', 'one-piece-of-shirt',
  'One Piece Of Shirt', 'Anime delusion for forbidden treasure', 1099,
  'Anime Delusions', 'Anime Meme Tee', 'Oversized', 'Grand line incident',
  'A white anime-meme tee for pirates, punchlines, and extremely questionable treasure maps.',
  'Manga-panel styling meets toilet humor. It is not subtle, which is exactly why it exists.',
  'Anime chaos with bathroom-wall confidence.', '230 GSM soft cotton',
  'Dispatches in 72 hours', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Manga-style front print', 'White tee base', 'Oversized fit']::TEXT[],
  '#f8f6ee', '#ffffff', '#111111', '#ffcf24', '#17120a',
  '/images/products/one-piece-of-shirt.png',
  ARRAY['/images/products/one-piece-of-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_william_shookspeare', 'WS', 'william-shookspeare',
  'William Shookspeare', 'Brainrot tee for literature damage', 1099,
  'Brainrot', 'Meme Tee', 'Relaxed', 'English class ruined',
  'A white tee for people who paid attention in class only when the joke was visual.',
  'Four Shakespeare variants, one deeply unnecessary pun, and enough academic nonsense to start a hallway conversation.',
  'Bookish, cursed, and teacher-approved by accident.', '220 GSM soft cotton',
  'Dispatches in 48 hours', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Four-panel meme print', 'White tee base', 'Relaxed fit']::TEXT[],
  '#f8f6ee', '#ffffff', '#111111', '#ff5f7a', '#17120a',
  '/images/products/william-shookspeare-shirt.png',
  ARRAY['/images/products/william-shookspeare-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_this_is_fine', 'TIF', 'this-is-fine', 'This Is Fine',
  'Brainrot tee for crisis management', 1199, 'Brainrot', 'Meme Tee',
  'Oversized', 'Everything fine',
  'A black tee for people handling disaster with a chair, a hat, and zero urgency.',
  'Bright fire graphic on a black base, made for anyone who calls a breakdown a learning experience.',
  'Panic, but make it cute.', '240 GSM combed cotton', 'Made to order in 4 days',
  ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Black oversized tee', 'Large cartoon front print', 'Heavy cotton feel']::TEXT[],
  '#101010', '#ffffff', '#ffd93d', '#f97316', '#ffffff',
  '/images/products/this-is-fine-shirt.png',
  ARRAY['/images/products/this-is-fine-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_hydration_duck', 'HD', 'hydration-duck', 'Hydration Duck',
  'Blue tee for desk survival', 999, 'Brainrot', 'Meme Tee', 'Relaxed',
  'Sip behavior',
  'A soft blue tee for people whose productivity system is mostly beverages and denial.',
  'Small front graphic, low-volume chaos, and the exact energy of opening a drink instead of fixing the problem.',
  'Quietly silly and extremely wearable.', '220 GSM soft cotton',
  'Dispatches in 48 hours', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Soft blue tee', 'Small front graphic', 'Relaxed daily fit']::TEXT[],
  '#86b5d8', '#ffffff', '#ffcf24', '#2563eb', '#17120a',
  '/images/products/hydration-duck-shirt.png',
  ARRAY['/images/products/hydration-duck-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
),
(
  'product_only_fans', 'OF', 'only-fans', 'Only Fans',
  'Grey tee for literal audiences', 999, 'Brainrot', 'Pun Tee', 'Relaxed',
  'Literal content',
  'A grey tee for people who respect wordplay more than they respect context.',
  'The safest possible interpretation of the phrase, printed with enough fans to remove all doubt.',
  'Obvious, dumb, and built for double takes.', '220 GSM cotton blend',
  'Dispatches in 48 hours', ARRAY['S', 'M', 'L', 'XL']::TEXT[],
  ARRAY['Grey tee base', 'Fan pun graphic', 'Relaxed fit']::TEXT[],
  '#b9b9b4', '#ffffff', '#111111', '#ffcf24', '#17120a',
  '/images/products/only-fans-shirt.png',
  ARRAY['/images/products/only-fans-shirt.png']::TEXT[],
  24, true, false, NOW(), NOW()
)
ON CONFLICT ("slug") DO UPDATE
SET "sku" = EXCLUDED."sku",
    "name" = EXCLUDED."name",
    "subtitle" = EXCLUDED."subtitle",
    "price" = EXCLUDED."price",
    "collection" = EXCLUDED."collection",
    "category" = EXCLUDED."category",
    "fit" = EXCLUDED."fit",
    "badge" = EXCLUDED."badge",
    "description" = EXCLUDED."description",
    "story" = EXCLUDED."story",
    "vibe" = EXCLUDED."vibe",
    "materials" = EXCLUDED."materials",
    "leadTime" = EXCLUDED."leadTime",
    "sizes" = EXCLUDED."sizes",
    "highlights" = EXCLUDED."highlights",
    "paletteBase" = EXCLUDED."paletteBase",
    "paletteShell" = EXCLUDED."paletteShell",
    "paletteAccent" = EXCLUDED."paletteAccent",
    "paletteGlow" = EXCLUDED."paletteGlow",
    "paletteText" = EXCLUDED."paletteText",
    "storefrontImage" = EXCLUDED."storefrontImage",
    "catalogImages" = EXCLUDED."catalogImages",
    "inventory" = GREATEST("Product"."inventory", EXCLUDED."inventory"),
    "active" = EXCLUDED."active",
    "updatedAt" = NOW();
